object Versions{
    const val CORE_KTX_VERSION = "1.7.0"
    const val APPCOMPAT_VERSION = "1.4.0"
    const val MATERIAL_VERSION = "1.4.0"
    const val CONSTRAINT_LAYOUT_VERSION = "2.1.2"
    const val JUNIT_VERSION = "4.0"
    const val EXT_JUNIT_VERSION = "1.1.3"
    const val ESPRESSO_CORE_VERSION = "3.4.0"
    const val CICERONE_VERSION = "7.1"
    const val MOXY_VERSION = "2.2.2"
    const val ROOM_VERSION = "2.4.0"
    const val OKHTTP_VERSION = "4.6.0"
    const val RETROFIT_VERSION = "2.9.0"
    const val RETROFIT_CONVERTER_GSON_VERSION = "2.7.1"
    const val RETROFIT_ADAPTER_RXJAVA3_VERSION = "2.9.0"
    const val RETROFIT_COROUTINES_ADAPTER_VERSION = "0.9.2"
    const val CONCRYPT_ANDROID_VERSION = "2.2.1"
    const val GLIDE_VERSION = "4.11.0"
    const val KOIN_VERSION = "3.1.2"
    const val COROUTINES_VERSION = "1.5.0"
    const val SPLASH_SCREEN_CORE_VERSION = "1.0.0-alpha01"
}